<a href="https://colab.research.google.com/github/rakibulislam0101/Numpy/blob/main/NeuralNine_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
!pip install numpy

In [ ]:
import numpy as np

a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [1,1,1,1],
    [2,2,2,2]

])
a.shape
a.ndim
a.size
a.dtype

dtype('int64')

In [ ]:
x = np.array([
    [1,2,3,4],
    [5,'Hello',7,8]

])
x.dtype

type(a[1][2])

numpy.int64

In [ ]:
y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

type(y[1][2])
y[1][2]

6

In [ ]:
d = {
    '1' : 'A'
}

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,d,8],
])
print(a.dtype)

object


In [ ]:
z = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
],dtype='U7')

z.dtype

dtype('<U7')

In [ ]:
a = np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
zero = np.zeros((3,3),dtype='int')
zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
one = np.ones((4,5),dtype='int')
one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.empty((5,5,5))
a

In [ ]:
x_values = np.arange(0,10,2)
x_values

array([0, 2, 4, 6, 8])

In [ ]:
y_values = np.arange(0,1000,5)
y_values

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495, 500, 505, 510, 515,
       520, 525, 530, 535, 540, 545, 550, 555, 560, 565, 570, 575, 580,
       585, 590, 595, 600, 605, 610, 615, 620, 625, 630, 635, 640, 645,
       650, 655, 660, 665, 670, 675, 680, 685, 690, 695, 700, 705, 710,
       715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765, 770, 775,
       780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835, 840,
       845, 850, 855, 860, 865, 870, 875, 880, 885, 890, 895, 90

In [ ]:
z_values = np.linspace(0,10,2)
z_values

x_values = np.linspace(0,25,5)
x_values

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

In [ ]:
import numpy as np

print(np.nan)
print(np.inf)
print(np.isnan(np.nan))
print(np.isinf(np.inf))

print(np.sqrt(-1))
print(np.array([10]) / 0)

nan
inf
True
True
nan
[inf]


<ipython-input-55-deaaf643a5c1>:8: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
<ipython-input-55-deaaf643a5c1>:9: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10]) / 0)


In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np.array(l1)
a2 = np.array(l2)

l1 * 5 #repeat 5 *
a1 * 5 #calculation all values

# difference between list and array

array([ 5, 10, 15, 20, 25])

In [ ]:
# vactor addition array

l3 = [1,2,3,4,5]
l4 = [6,7,8,9,10]

a3 = np.array(l3)
a4 = np.array(l4)

print(a3+a4)

[ 7  9 11 13 15]


In [ ]:
a = np.array([1,2,3])
b = np.array([
    [1],
    [2]
])

print(a+b)

[[2 3 4]
 [3 4 5]]


In [ ]:
import numpy as np

a = np.array([1,2,3])

a = np.append(a, [7,8,9])
print(a)

[1 2 3 7 8 9]


In [ ]:
import numpy as np

a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
])

a.shape

(4, 5)

In [ ]:
b = a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
])

b.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
c = np.arange(1,21)
c

d = np.resize(c,(4,5))
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
a = np.random.randint(1,10,(4,4))
a

print(a.flatten())
print(a.ravel())

[6 1 9 5 7 8 1 5 4 1 3 7 5 7 1 8]
[6 1 9 5 7 8 1 5 4 1 3 7 5 7 1 8]


In [ ]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
])

a.transpose()

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [ ]:
import numpy as np

a1 = np.array([
    [1,2,3,4,5]
])

a2 = np.array([
    [6,7,8,9,10]
])

a = np.concatenate((a1,a2))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
import numpy as np

x = np.random.randint(1,10,(4,4))
x

array([[5, 4, 2, 1],
       [1, 8, 9, 4],
       [6, 7, 6, 6],
       [8, 7, 1, 1]])

In [ ]:
print(x.max())
print(x.min())
print(x.mean())
print(x.std())
print(x.sum())
print(np.median(a))

9
1
4.75
2.7271780286589284
76
5.5


In [ ]:
import numpy as np

x = np.random.randint(0,100,(3,4,4))
x

array([[[52, 63, 35, 48],
        [59, 97, 44, 80],
        [74, 40, 41, 32],
        [ 4, 31, 14, 17]],

       [[47, 32, 44, 71],
        [43, 22, 28, 87],
        [41, 99, 41, 72],
        [63, 63, 34, 89]],

       [[42,  3, 61, 38],
        [97, 40, 89, 35],
        [27,  8,  3, 23],
        [48, 76, 47, 54]]])

In [ ]:
numbers = np.random.binomial(10, p=0.5, size=(5,10))
numbers

array([[4, 5, 3, 4, 5, 4, 3, 5, 4, 8],
       [7, 7, 5, 5, 4, 6, 7, 6, 2, 5],
       [3, 5, 5, 6, 6, 3, 5, 7, 6, 7],
       [6, 4, 5, 4, 3, 4, 5, 4, 3, 4],
       [7, 4, 6, 3, 5, 3, 5, 7, 6, 7]])

In [ ]:
n = np.random.choice([10,20,30,40,50],size=(5,10))
n

array([[20, 30, 50, 50, 30, 10, 20, 10, 30, 40],
       [30, 50, 20, 30, 20, 50, 30, 50, 40, 10],
       [10, 40, 20, 20, 50, 20, 50, 20, 40, 10],
       [40, 40, 40, 30, 20, 30, 30, 20, 10, 40],
       [50, 20, 30, 10, 20, 40, 30, 50, 20, 20]])