<a href="https://colab.research.google.com/github/rakibulislam0101/Numpy/blob/main/Self_study_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

x = np.array([
    [1,2,3,4,5]
])
x

array([[1, 2, 3, 4, 5]])

In [ ]:
a = np.array([
    [1,2,3,4,5],
    [1,5,9,3,4]
])
a.shape

(2, 5)

In [ ]:
b = np.array([[
    [1,2,3,6],
    [1,4,8,9]
]])
b.ndim

y = np.array([[
    [1,5,9,7,5,3],
    [3,5,7,1,6,8],
]])
y.ndim
y.shape

(1, 2, 6)

In [ ]:
# c = np.array([
#     [1,2,3,4,5]
# ])
# c.dtype

d = np.random.randint(1,10,(11,11))

d.dtype
d

array([[6, 6, 7, 5, 8, 5, 1, 8, 9, 4, 7],
       [1, 2, 3, 4, 8, 9, 4, 7, 7, 7, 7],
       [4, 5, 2, 2, 9, 2, 3, 6, 1, 2, 4],
       [4, 1, 6, 9, 9, 9, 7, 2, 1, 2, 1],
       [2, 9, 2, 2, 9, 3, 6, 4, 1, 7, 5],
       [5, 4, 1, 5, 9, 1, 9, 6, 3, 6, 5],
       [9, 8, 9, 7, 1, 4, 7, 7, 5, 7, 7],
       [6, 4, 7, 1, 4, 1, 7, 1, 1, 4, 2],
       [4, 2, 3, 4, 2, 9, 1, 8, 7, 1, 4],
       [4, 9, 1, 7, 5, 6, 9, 6, 8, 3, 6],
       [9, 5, 6, 2, 7, 9, 6, 1, 9, 2, 7]])

In [ ]:
a = np.random.randint(1,30,(7,7))
a.size
a

array([[24, 25, 21,  2, 21, 28, 29],
       [ 3, 15,  6,  7,  4, 11, 29],
       [13, 16,  8,  9, 17, 23, 12],
       [ 7, 23, 24, 23, 27, 12, 20],
       [ 2, 24,  2, 16, 17,  9, 18],
       [ 6, 11, 22, 22, 29, 22,  8],
       [28, 26,  4, 11, 24, 26, 20]])

In [ ]:
x = np.zeros((3,3))
x

y = np.zeros((4,4),dtype='int')
y

z = np.zeros((3,3,3),dtype='int')
z.size
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
x = np.ones((3,2,3),dtype='int')
x

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [ ]:
x = np.array([[
    [1,2,3,4,5],
    [1,5,9,3,4],
    [8,5,2,1,4],
]])

a = np.array([
    [2,5,8],
    [3,5,4],
    [1,4,7]
])

b = np.array([[
    [12,36,10,15,18]
]])

y = np.random.randint(1,20,(3,3))

z = np.random.randint(1,15,(4,4))

x.nbytes, a.nbytes, b.nbytes, y.nbytes, z.nbytes

(120, 72, 40, 72, 128)

In [ ]:
x = np.random.randint(1,10,(3,3))

y = np.random.randint(1,5,(2,2))
x.data, y.data

(<memory at 0x7d3ef617fe00>, <memory at 0x7d3ef617fed0>)

In [ ]:
x = np.full((3,3),5)
x

y = np.full((4,4),1)
y

z = np.full((5,5),9)
z

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [ ]:
a = np.identity(3,dtype='int')
a

b = np.identity(4, dtype='int')
b

c = np.identity(3,dtype='int')
c

d = np.identity(5, dtype='int')
d

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
d[0][0]

1

In [ ]:
A = np.random.randint(1,10, (3,3))
A

B = np.random.randint(1,15, size=(3,3,3))
B

array([[[ 7, 11, 12],
        [ 1,  2,  8],
        [10,  1, 13]],

       [[12, 13,  8],
        [ 8,  9, 11],
        [ 1,  5,  1]],

       [[13,  7,  4],
        [10,  5,  7],
        [ 7, 10,  1]]])

In [ ]:
X = np.arange(1,10)
X

Y = np.arange(1,6)
Y

A = np.arange(1,11)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
import numpy as np

x = np.random.randint(1,10,(3,2))


array([[2, 2],
       [6, 1],
       [7, 9]])

In [ ]:
np.reshape(x,(2,3))

array([[2, 2, 6],
       [1, 7, 9]])

In [ ]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

a_resize = np.resize(a,(2,4))
a_resize

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
x = np.random.randint(1,15,(3,4))
x

array([[10,  6, 13,  5],
       [ 8, 10,  1,  4],
       [ 4,  6,  4,  7]])

In [ ]:
x_ravel = np.ravel(x)
x_ravel

array([10,  6, 13,  5,  8, 10,  1,  4,  4,  6,  4,  7])

In [ ]:
y = np.random.randint(1,20,(9,9))
y

array([[10, 11,  3, 10,  2,  6, 12,  4,  6],
       [ 8,  5, 13, 12, 11, 14, 19,  7,  5],
       [ 1, 18,  2, 19, 16, 19, 15, 11, 13],
       [12, 13,  6,  9,  9,  9,  7, 18, 16],
       [14, 16, 17,  6,  6, 16,  1, 11,  6],
       [ 5,  5,  4, 16, 11,  9, 10,  1,  5],
       [17, 16,  2, 17,  1,  1, 10, 17,  2],
       [19,  8, 11, 17,  2, 18, 11,  6, 14],
       [14,  4, 19, 18, 10,  7, 10,  2, 13]])

In [ ]:
y_ravel = np.ravel(y)
y_ravel

array([10, 11,  3, 10,  2,  6, 12,  4,  6,  8,  5, 13, 12, 11, 14, 19,  7,
        5,  1, 18,  2, 19, 16, 19, 15, 11, 13, 12, 13,  6,  9,  9,  9,  7,
       18, 16, 14, 16, 17,  6,  6, 16,  1, 11,  6,  5,  5,  4, 16, 11,  9,
       10,  1,  5, 17, 16,  2, 17,  1,  1, 10, 17,  2, 19,  8, 11, 17,  2,
       18, 11,  6, 14, 14,  4, 19, 18, 10,  7, 10,  2, 13])

In [ ]:
a = np.random.randint(1,10,(3,4)).reshape(4,3)
a

b = np.array([[
    [1,2,3,4,5],
    [1,2,3,4,5]

]]).reshape(5,2)
b

array([[1, 2],
       [3, 4],
       [5, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:

x = np.array([[
    [1,2,3],
    [6,7,8]
]])

y = np.array([[
    ['X','Y','Z'],
    ['A','B','C']
]])

np.hstack((x,y))

array([[['1', '2', '3'],
        ['6', '7', '8'],
        ['X', 'Y', 'Z'],
        ['A', 'B', 'C']]], dtype='<U21')

In [ ]:
x = np.array([[
    [1,2,3],
    [6,7,8]
]])

y = np.array([[
    ['X','Y','Z'],
    ['A','B','C']
]])

np.column_stack((x,y))

array([[['1', '2', '3'],
        ['6', '7', '8'],
        ['X', 'Y', 'Z'],
        ['A', 'B', 'C']]], dtype='<U21')

In [ ]:
x = np.array([[
    [1,2,3],
    [6,7,8]
]])

y = np.array([[
    ['X','Y','Z'],
    ['A','B','C']
]])

np.vstack((x,y))

array([[['1', '2', '3'],
        ['6', '7', '8']],

       [['X', 'Y', 'Z'],
        ['A', 'B', 'C']]], dtype='<U21')

In [ ]:
x = np.array([[
    [1,2,3],
    [6,7,8]
]])

y = np.array([[
    ['X','Y','Z'],
    ['A','B','C']
]])

np.row_stack((x,y))

array([[['1', '2', '3'],
        ['6', '7', '8']],

       [['X', 'Y', 'Z'],
        ['A', 'B', 'C']]], dtype='<U21')

In [ ]:
import numpy as np
x = np.array([
    [1,1,1,1],
    [2,2,2,2]
])

y = np.array([
    [1,1,1,1],
    [2,2,2,2]
])

np.dstack((x,y))

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2],
        [2, 2],
        [2, 2]]])

In [ ]:
# np.array()
# shape
# ndim
# dtype
# size
# zeros
# ones
# nbytes
# data
# np.full
# np.identity
# np.arange
# np.reshape
# np.resize
# np.ravel
# np.hstack
# np.column_stack
# np.vstack
# np.row_stack
# np.dstack

In [ ]:
x = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
])

np.resize(x,(2,2))

array([[1, 2],
       [3, 4]])

In [ ]:
a = np.array([
    [1,2,3,4,5],
    [2,2,3,4,5]
])

b = np.array([
    [6,7,8,9,10],
    [6,7,8,9,10]
])

c = np.dstack((a,b))
c

array([[[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]],

       [[ 2,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]])

In [ ]:
import numpy as np

list_ = [1,2,3,4,5,6,7,8,9,10]

Array = np.array(list_)

Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
import numpy as np

X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

X.shape

Y = np.array([
    [1,2,3,4],
    [2,4,6,8]
])

Y.reshape(4,2)

array([[1, 2],
       [3, 4],
       [2, 4],
       [6, 8]])

In [ ]:
a = np.array([
    [2,4,6,8,10],
    [1,3,5,7,9],
    [2,5,7,9,13]
])

a.shape

(3, 5)

In [ ]:
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

b.ndim

2

In [ ]:
y = np.array([
    [1.0,2,3,4,5]
])
y.dtype

z = np.array([1,2,3,4,5])
z.dtype

dtype('int64')

In [ ]:
a = np.array([
    [1,5,9],
    [3,5,7],
    [7,5,3],
])

a.size

b = np.array([
    [1,2,3,4,5,6,7,8]
])
b.size

8

In [ ]:
z = np.zeros((4,4,4))
z

c = np.zeros((3,2,2),dtype='int')
c

d = np.zeros((2,3,3))
d

e = np.zeros((1,3,3),dtype='int')
e

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
o = np.ones((3,2,4),dtype='int')
o

x = np.ones((4,5,5))
x.ndim
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
a.nbytes, y.nbytes, z.nbytes, o.nbytes, x.nbytes

(72, 40, 512, 192, 800)

In [ ]:
a.data, y.data, z.data, o.data, x.data

(<memory at 0x7c8622383780>,
 <memory at 0x7c8621f205e0>)

In [ ]:
f_1 = np.full((4,4),9)
f_1

f_2 = np.full((3,3),3)
f_2

f_3 = np.full((4,4),5)
f_3

f_4 = np.full((2,5),7)
f_4

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
i_1 = np.identity(4, dtype='int')
i_1

i_2 = np.identity(5,dtype='int')
i_2

i_3 = np.identity(3)
i_3

i_4 = np.identity(7,dtype='int')
i_4

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
r =  np.random.randint(1,10,(2,2))
r

t = np.random.randint(1,20,size=(3,3,3))
t

array([[[ 7,  9, 19],
        [14, 12,  2],
        [ 6, 14, 11]],

       [[12, 17, 12],
        [ 6, 13, 13],
        [17, 15, 16]],

       [[ 2, 19, 14],
        [19, 19, 19],
        [ 1,  5,  6]]])

In [ ]:
A = np.random.randint(1,10,size=(3,3,3))
A

array([[[6, 8, 2],
        [1, 7, 6],
        [1, 4, 1]],

       [[7, 3, 6],
        [9, 3, 5],
        [7, 6, 1]],

       [[7, 3, 7],
        [6, 5, 4],
        [6, 9, 3]]])

In [ ]:
A[1][1][2]

5

In [ ]:
a = np.arange(1,20)
a

b = np.arange(1,10)
b[:5]

c =np.arange(1,16)
c[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

a_resize = np.resize(x,(2,2))
a_resize

array([[1, 2],
       [3, 4]])

In [ ]:
y = np.array([
    [1,5,9,8,5],
    [3,5,7,1,6],
    [8,6,2,1,7]
])

y_resize = np.resize(y,(3,2))
y_resize

array([[1, 5],
       [9, 8],
       [5, 3]])